// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaEventDefinition;

  NanikaEventDefinition = this.NanikaEventDefinition;

  if (NanikaEventDefinition == null) {
    NanikaEventDefinition = {};
  }

  NanikaEventDefinition.version = {
    request: {
      submethod: 'Version',
      id: 'version'
    }
  };

  NanikaEventDefinition.name = {
    request: {
      submethod: 'String',
      id: 'name'
    }
  };

  NanikaEventDefinition.craftman = {
    request: {
      submethod: 'String',
      id: 'craftman'
    }
  };

  NanikaEventDefinition.craftmanw = {
    request: {
      submethod: 'String',
      id: 'craftmanw'
    }
  };

  this.NanikaEventDefinition = NanikaEventDefinition;

}).call(this);
