// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaEventDefinition;

  NanikaEventDefinition = this.NanikaEventDefinition;

  if (NanikaEventDefinition == null) {
    NanikaEventDefinition = {};
  }

  NanikaEventDefinition.close = {
    request: {
      id: 'OnClose',
      headers: {
        reason: 0
      }
    }
  };

  NanikaEventDefinition.closeall = {
    request: {
      id: 'OnCloseAll',
      headers: {
        reason: 0
      }
    }
  };

  NanikaEventDefinition.changing = {
    request: {
      id: 'OnGhostChanging',
      headers: {
        to_sakuraname: 0,
        reason: 1,
        to_name: 2,
        to_path: 3
      }
    }
  };

  this.NanikaEventDefinition = NanikaEventDefinition;

}).call(this);
