// Generated by CoffeeScript 1.8.0

/* (C) 2014 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2014 */

(function() {
  var NanikaEventDefinition, bool;

  NanikaEventDefinition = this.NanikaEventDefinition;

  if (NanikaEventDefinition == null) {
    NanikaEventDefinition = {};
  }

  bool = function(value, nanika, request_args, optionals) {
    if (value) {
      return 1;
    } else {
      return 0;
    }
  };

  NanikaEventDefinition.secondchange = {
    request: {
      id: 'OnSecondChange',
      headers: {
        os_uptime: 0,
        mikire: {
          name: 1,
          value: bool
        },
        overlapped: {
          name: 2,
          value: bool
        },
        cantalk: {
          name: 3,
          value: bool
        }
      }
    }
  };

  NanikaEventDefinition.minutechange = {
    request: {
      id: 'OnMinuteChange',
      headers: {
        os_uptime: 0,
        mikire: {
          name: 1,
          value: bool
        },
        overlapped: {
          name: 2,
          value: bool
        },
        cantalk: {
          name: 3,
          value: bool
        }
      }
    }
  };

  this.NanikaEventDefinition = NanikaEventDefinition;

}).call(this);
